"""add research metadata to messages

Revision ID: 9cc386f7fec3
Revises: a2cda31fd3b9
Create Date: 2026-08-16 17:33:58.318800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc386f7fec3'
down_revision: Union[str, Sequence[str], None] = 'a2cda31fd3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'metadata')
    # ### end Alembic commands ###
